# Generated by Django 5.2.14 on 2026-05-18 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyplayed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recentlyplayed',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_recently_played'),
        ),
    ]
