# Generated by Django 5.2.14 on 2026-05-18 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('cover_url', models.URLField(max_length=1024)),
                ('audio_url', models.URLField(max_length=1024)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
